Update README to follow Heroku best practices for buildpacks
DataDog/heroku-buildpack-datadog pull request #231
Opened 2020-12-22 15:24 UTC by arapulido

Update install instructions to recommend not pinning the buildpack. Fixes #229

Remove alert-warning div, as it wasn't being rendered correctly in the docs site

2020-12-22 15:39 UTC, jeremy-lq commented on README.md
> -<div class="alert alert-warning">
Can use standard links if we want to retain the warning. No strong preference.

2020-12-22 15:43 UTC, jeremy-lq requested changes

2020-12-22 15:43 UTC, jeremy-lq commented on README.md
> +In both cases, the version of the Datadog agent can be pinned as well by setting `DD_AGENT_VERSION` environment variable.
Suggest:

By default, the buildpack pins the latest version of the Datadog Agent at the time of release. You can pin the Agent to an earlier version by setting the `DD_AGENT_VERSION` environment variable.

2020-12-22 16:31 UTC, jeremy-lq approved these changes

2020-12-22 16:32 UTC, merged

2020-12-22 17:55 UTC, agrobbin commented
@arapulido does this mean that an upgrade to the buildpack version (and by extension the agent version) no longer requires a purging of the Heroku build cache?

2021-01-15 09:16 UTC, arapulido commented
@agrobbin Good point. This is still necessary, but I understand that if you are using master, then it is more difficult to know when this is coming. I will work on this to make it automated when the agent version changes.