Easily enable the Redis and Postgres integrations
DataDog/heroku-buildpack-datadog pull request #324
Opened 2023-02-08 10:23 UTC by arapulido

Redis and Postgres are two integrations that are very popular in Heroku applications.

Datadog Heroku buildpack users usually need to configure these integrations by maintaining long prerun scripts.

This feature enables these integrations and configure them with their basic options by just setting an environment variable in the Heroku applications.

2023-02-09 01:27 UTC, buraizu requested changes
Thanks for the PR, left a few suggestions.

2023-02-09 01:27 UTC, buraizu commented on README.md
> +By default, this integration assumes the Redis connection URL is defined in an environement variable called `REDIS_URL` (this is default for Heroku Data for Redis and other addons).
```suggestion
By default, this integration assumes the Redis connection URL is defined in an environment variable called `REDIS_URL` (this is the default configuration for Heroku Data for Redis and other Redis add-ons).
```

2023-02-09 01:27 UTC, buraizu commented on README.md
> +By default, this integration assumes the Redis connection URL is defined in an environement variable called `REDIS_URL` (this is default for Heroku Data for Redis and other addons).
Let me know if the changes here interfere with the intended meaning.

2023-02-09 01:27 UTC, buraizu commented on README.md
> +If your connection URL is defined in a different environment variable, set the `REDIS_URL_VAR` environment variable to the name of the variable name. For example, if you're using Redis Enterprise Clo
```suggestion
If your connection URL is defined in a different environment variable, set the `REDIS_URL_VAR` environment variable to the variable name. For example, if you're using Redis Enterprise Cloud, set it to `REDISCLOUD_URL`:
```

2023-02-09 01:27 UTC, buraizu commented on README.md
> +If you are using a Postgres addon in your Heroku application (for example, Heroku Postgres), you can easily enable the Datadog Postgres integration by setting an envionment variable:
```suggestion
If you are using a Postgres add-on in your Heroku application (for example, Heroku Postgres), you can enable the Datadog Postgres integration by setting an environment variable:
```

2023-02-09 01:27 UTC, buraizu commented on README.md
> +By default, this integration assumes the Postgres connection URL is defined in an environement variable called `DATABASE_URL` (this is default for Heroku Postgres and other addons).
```suggestion
By default, this integration assumes the Postgres connection URL is defined in an environment variable called `DATABASE_URL` (this is the default configuration for Heroku Postgres and other Postgres add-ons).
```

2023-02-09 01:27 UTC, buraizu commented on README.md
> +If your connection URL is defined in a different environment variable, set the `POSTGRES_URL_VAR` environment variable to the name of the variable name.
```suggestion
If your connection URL is defined in a different environment variable, set the `POSTGRES_URL_VAR` environment variable to the variable name.
```

2023-02-09 01:27 UTC, buraizu commented on extra/datadog.sh
> +  # The connection URL is, by default DATABASE_URL, but can be configured by the user
```suggestion
  # The default connection URL is DATABASE_URL, but can be configured by the user
```

2023-02-09 01:27 UTC, buraizu commented on extra/datadog.sh
> +  # The connection URL is, by default REDIS_URL, but can be configured by the user
```suggestion
  # The default connection URL is REDIS_URL, but can be configured by the user
```

2023-02-09 08:47 UTC, arapulido commented
> Thanks for the PR, left a few suggestions.

Thanks for the review and suggestions. Those are now applied!

2023-02-09 18:58 UTC, buraizu approved these changes
Thanks for applying those changes. I left one minor additional suggestion that's optional, but overall this LGTM!

2023-02-09 18:58 UTC, buraizu commented on extra/datadog.sh
> +  # The default connection URL is DATABASE_URL, but can be configured by the user
```suggestion
  # The default connection URL is set in DATABASE_URL, but can be configured by the user
```

2023-02-09 18:58 UTC, buraizu commented on extra/datadog.sh
> +  # The default connection URL is REDIS_URL, but can be configured by the user
```suggestion
  # The default connection URL is set in REDIS_URL, but can be configured by the user
```

2023-02-10 14:18 UTC, jeremy-lq approved these changes

2023-02-15 14:06 UTC, merged